### ISSUE TITLE
Build failure with hashable >= 1.3.4

### ISSUE THREAD

**Issue by sjakobi** [zgrannan/rest#3]
```
src/Language/REST/Types.hs:72:10: error:
    Duplicate instance declarations:
      instance Hashable a => Hashable (OS.Set a)
        -- Defined at src/Language/REST/Types.hs:72:10
      instance Hashable v => Hashable (OS.Set v)
        -- Defined in ‘hashable-1.3.5.0:Data.Hashable.Class’
   |
72 | instance Hashable a => Hashable (OS.Set a) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/REST/Types.hs:75:10: error:
    Duplicate instance declarations:
      instance (Hashable a, Hashable b) => Hashable (M.Map a b)
        -- Defined at src/Language/REST/Types.hs:75:10
      instance (Hashable k, Hashable v) => Hashable (M.Map k v)
        -- Defined in ‘hashable-1.3.5.0:Data.Hashable.Class’
   |
75 | instance (Hashable a, Hashable b) => Hashable (M.Map a b) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build rest-rewrite-0.1.1
```
https://github.com/zgrannan/rest/commit/5f71ee2131e79363be1d7257248ab2adbbddfffd already added the necessary bound on `hashable`. Could you publish it as a Hackage revision?

**Comment by curiousleo** [comment]
This same error occurred [on Hackage](https://hackage.haskell.org/package/rest-rewrite-0.1.1/reports/2), preventing it from building [any documentation](https://hackage.haskell.org/package/rest-rewrite-0.1.1).

**Comment by sjakobi** [comment]
As a Hackage trustee I have created revisions for v0.1 and v0.1.1 that should prevent users from encountering these errors. See

* https://hackage.haskell.org/package/rest-rewrite-0.1/revisions/
* https://hackage.haskell.org/package/rest-rewrite-0.1.1/revisions/

**Comment by zgrannan** [comment]
Thanks for the report, and sorry for the delay. I've uploaded a new version of REST with some additional changes, including increasing the upper bound. New version is here: https://hackage.haskell.org/package/rest-rewrite-0.2.0.
