### ISSUE TITLE
Ensure test directory `graphs/` exists

### ISSUE THREAD

**Issue by tbidne** [zgrannan/rest#37]
Hello!

When trying to build this project in nixpkgs, we have noticed a [problem](https://github.com/NixOS/nixpkgs/pull/240235): The `graphs/` directory, required for the tests to succeed, does not necessarily exist, as it is not part of the cabal distribution (see [this comment](https://github.com/NixOS/nixpkgs/pull/240235#discussion_r1244625262)). To see this, run `cabal sdist`, extract the `.tar.gz`, and observe that the `graphs/` directory does not exist:

```
[.../rest/dist-newstyle/sdist/rest-rewrite-0.4.1]$ ls
LICENSE  rest-rewrite.cabal  src  test  testlib
```

The easiest way to fix this is to manually specify the folder in your cabal file:

```diff
diff --git a/rest-rewrite.cabal b/rest-rewrite.cabal
index 5a0ffc9..c975686 100644
--- a/rest-rewrite.cabal
+++ b/rest-rewrite.cabal
@@ -10,6 +10,9 @@ description:        REST is a Rewriting library with online termination checking
 synopsis:           Rewriting library with online termination checking
 license-file:       LICENSE
 
+extra-source-files:
+  graphs/.DONOTDELETE
+
 source-repository head
   type:     git
   location: https://github.com/zgrannan/rest
```

This ensures the directory is copied over, so the tests can pass.
```
[...rest/dist-newstyle/sdist/rest-rewrite-0.4.1]$ ls
graphs  LICENSE  rest-rewrite.cabal  src  test  testlib
```

Alternatively, you could use [`createDirectory`](https://hackage.haskell.org/package/directory-1.3.8.1/docs/System-Directory.html#v:createDirectory) to ensure it is exists [here](https://github.com/zgrannan/rest/blob/master/src/Language/REST/Dot.hs#L96).

Would a PR with either of these changes be accepted?

Thanks for the great package!

**Comment by zgrannan** [comment]
Yes, either approach is good and I’ll accept the PR!

Thank you!!

**Comment by tbidne** [comment]
Thanks!
