### ISSUE TITLE
Relax upper bound for `containers` to allow 0.7

### ISSUE THREAD

**Issue by ulysses4ever** [zgrannan/rest#43]
Otherwise, LiquidHaskell can't build with GHC 9.10.

**Comment by facundominguez** [comment]
It was implemented in https://github.com/zgrannan/rest/pull/41 already, but there needs to be a hackage release or a hackage revision to update the bound.

**Comment by zgrannan** [comment]
New release: https://hackage.haskell.org/package/rest-rewrite-0.4.4

@facundominguez should I add you as a maintainer on hackage so you can publish new releases yourself? If so just let me know your username

**Comment by facundominguez** [comment]
Thanks @zgrannan. I wouldn't mind publishing releases myself. My hackage username is FacundoDominguez.
