### ISSUE TITLE
Why aren't constraints refined when deciding to explore

### ISSUE THREAD

**Issue by facundominguez** [zgrannan/rest#9]
With the aim to understand the code better, I found that in section 6.4 of the REST paper the explorable predicate goes like this
```
explorable(t, c).= not (t ∈ M) ∨ (¬(c ⇒ M[t]) ∧ ∃u.(t → u ∧ explorable(u, c)))
```

Why is the constraint not refined in the recursive call as in
```
explorable(t, c).= not (t ∈ M) ∨ (¬(c ⇒ M[t]) ∧ ∃u.(t → u ∧ explorable(u, refine(c, t, u))))
```
?

**Comment by zgrannan** [comment]
Wow, you clearly understand this paper very well!! I think actually your version is better, it is still correct (only exploring terms when necessary), and will not explore some terms that are erroneously explored in the first version.

Just to provide some intuition, which is probably obvious to you already.

Namely, suppose that we have `c0` and  `c1`, where `c0` is strictly less restrictive than `c1`. Assume we have `t0` explored at `c0`, `t1` explored at `c1`. In the current version, there is a possible rewrite `t0 -> t1`, then it will always be explored from `c0`. But with your version, if `refine(c0, t0, t1)` is strictly more restrictive (or equal to) `c1`, then `t0` would not be explored.

I think this change should definitely be made, as it may improve performance a bit. If you're interested in giving it a try the relevant code is here: https://github.com/zgrannan/rest/blob/1cadb23edfbc393245ae964315b07f5c8581ea9f/src/Language/REST/ExploredTerms.hs#L56

**Comment by facundominguez** [comment]
Glad to have gotten something right out of the reading :)

I'll try updating `isFullyExplored` if you don't get to it first.

**Comment by zgrannan** [comment]
Implemented this in https://github.com/zgrannan/rest/pull/20!
